### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by uwabami** [tdiary/tdiary-style-gfm#17]
こんにちは。

gemspec には spec.license = "MIT" となっていますが、同梱の LICENSE.txt は GPL-3 です。
これはどれが正しいのでしょうか?

**Comment by hsbt** [comment]
@uwabami MIT は rubygems の雛型の修正漏れなので、GPL-3 が正解です。直してリリースし直しておきます。

**Comment by hsbt** [comment]
@uwabami https://github.com/tdiary/tdiary-style-gfm/releases/tag/v0.4.1 としてリリースし直しました。

**Comment by uwabami** [comment]
ありがとうございました!
